server/network/aoprotocol.py
https://github.com/AttorneyOnline/tsuserver3/commit/eb9d4ab7cd4c42c4c39720161f3349665474c26a for KFO
=> Removes null chars from input after it has been decoded into a utf-8 string

server/commands/roleplay.py
=> Only report sum of dice roll if rolling more than one die

server/commands/character.py
There may be a better solution, but moving these two lines of code seems to fix it
=> Fix /keys_remove not working (again)

server/network/aoprotocol.py
=> reset char folder if caught iniswapping

server/area_manager.py, server/network/aoprotocol.py
i really don't need it if i only have 1 hub
=> Only show Hub Switcher when there is more than 1 Hub

config_sample/config.yaml, requirements.txt, server/network/masterserverclient.py
(cherry picked from commit 17acb1a2625f82532affc7741de37ada093c7320)
I make no guarantees that this will actually work, so someone please TEST this before CW presses the big haha merge button.
=> Switch to HTTP API for advertising on server list

server/network/aoprotocol.py, server/tsuserver.py
i think i caught all the parameters that can be fucked with
this adds a setting that tries to prevent users from breaking out of their assigned character folders
=> Relative paths

server/tsuserver.py
i banned ASN 4
and it turns out that in turn all IPs starting with 4 couldn't join anymore
=> only apply ip ranges that end with a dot

server/network/webhooks.py, server/tsuserver.py
=> Forgot avatar URL

server/tsuserver.py
aliases are in reality just banned words
=> comment copypasta mistake

config_sample/config.yaml, server/client_manager.py, server/commands/areas.py, server/network/aoprotocol.py, server/tsuserver.py
5 messages in 5 seconds ist actually kinda fast if you think about it.
Prevents silly scripts that change the area status over and over.
=> OOC flood protection

config_sample/url.txt, server/client_manager.py, server/tsuserver.py
we had people play ip loggers
kinda risky to allow that
if you want to disable this feature just put "http" in the url.txt file
=> music url whitelisting

.github/workflows/pythonapp.yml, server/network/aoprotocol.py
- the CI now also runs on branches so it's obvious when you make a mistake on a feature branch
- client exceptions will now print to console instead of just disconnecting the client without doing anything
=> CI and Exception handler

config_sample/server_links.yaml, server/client_manager.py, server/network/aoprotocol.py, server/tsuserver.py
- Now the user links are fetched when you join the server, after receiving the "rd" (DONE) packet.
- The client's user link now is removed after they get disconnected.
- Fixed some exploits, now bad actors cannot have absolute control over the user links of others anymore.
- Added a self clear option, so the client can clear their own user link.
- Fixed a bug where user links were treated as server links.
- Fixed some minor bugs (_See commits for more details_)
**New features:**
_Server links:_
Now the server can declare the server links!
On a new config file called "server_links.yaml"
Useful for putting the content link, the discord, webpage, etc.
=> AOG RC1 hotfix

config_sample/config.yaml, server/network/masterserverclient.py
_[muffled my hope will never die playing in the distance]_
Add secure websockets to master server advertising.
=> Advertise secure websockets again

config_sample/command_aliases.yaml, config_sample/config.yaml, server/area_manager.py, server/client_manager.py, server/commands/areas.py
Add the command /gethubs to send info about all hubs
=> Add the command /gethubs

server/area_manager.py, server/client_manager.py, server/commands/roleplay.py
TODO:
/rps by itself displays rules, /rps [choice] submits a choice Winner is announced when 2 opponents fight each other
=> Add a Rock Paper Scissors command

server/area.py, server/client_manager.py, server/commands/battle.py, storage/battlesystem/hero.yaml
Added:
- New commands to join and create a guild
- Team Battle
- Mana and move mana cost
- New status and battle effects
- Rejoin to the battle when someone disconnects
=> Mana   new status   disconnected fighters guild

config_sample/command_aliases.yaml, docs/commands.md, server/area.py, server/client_manager.py, server/commands/music.py, server/tsuserver.py
- /musiclist_save Local/Area/Hub MusiclistName  
Allow you to save a musiclist on server list!
If the musiclist is already in the server list, you don't have to add MusiclistName
- /musiclist_add Local/Area/Hub Category MusicName Url
Allow you to add a song in a musiclist!
Remember to insert also Music extension in MusicName
- /musiclist_remove Local/Area/Hub Category MusicName
Allow you to remove a song from a musiclist!
Remember to insert also Music extension in MusicName
=> adding musiclist creation commands

config_sample/config.yaml, server/client_manager.py, server/commands/messaging.py, server/network/webhooks.py, server/tsuserver.py
=> Send discord need message

server/discordbot.py
- Renames getareas to gethubs
- Message splitting when char limit is reached
=> Improve area information retrieval on discord

server/area.py, server/network/aoprotocol.py, server/tsuserver.py
no parsing for DRO client yet, that'll come up in a bit. This supports KFO-Client video playback only for now
=> Add support for video playback in KFO-Client!
