config_sample/config.yaml
server/area.py
server/discordbot.py
server/network/aoprotocol.py
server/tsuserver.py
start_server.py

Introduces a very robust integarted Discord Bridge to KFO-Server. Features include:
- Webhook-based representation of speaking characters in the selected channel
- Setup isn't too difficult, requires you to obtain a Discord Bot according to [this guide](https://discordpy.readthedocs.io/en/latest/discord.html)
- Do not give the bot any permissions - the bot only needs permissions to the one channel you intend to use for the bridge. The channel permissions the bot needs are "read messages", "send messages" and "manage webhooks".
- Set up the config.yaml properly. `bridgebot_token` is your Discord Bot token, `bridgebot_channel` is the channel on your Discord for the bot to access, `bridgebot_character` is the on-server character folder to use, `bridgebot_emote` is the emote of said character …

Discord Bridge Bot setup

---

server/area.py
server/area_manager.py
server/client_manager.py
server/commands/hubs.py

Pretty much like the already established "_character_ enters from/leaves to..." OOC message, but IC now and togglable for GMs. I couldn't think of a better name for the command, so this is kinda provisional. Also wasn't too sure about "_character_ arrives", so might as well change it if the other way looks better.

Add /toggle_passingmsg command

---

server/client_manager.py
server/network/aoprotocol.py

Player count update

---

server/network/aoprotocol_ws.py

This helps when the websockets are behind a proxyserver, like Cloudflare

Add ability to read forwarded-for header.

---

server/network/aoprotocol.py

* Sends noencrypt flag to disable fantacrypt communication for clients older than 2.9

Fix incorrect decryptor argument

---

server/client_manager.py

```
2022-07-10 14:58:17|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|Okay you need a multiclient and be on web
2022-07-10 14:59:15|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|Pair with your own multiclient, make sure you're paired properly.
2022-07-10 14:59:23|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|Go to an area where iniswap is enabled.
2022-07-10 14:59:31|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|And speak with the iniswapped character.
2022-07-10 14:59:41|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|Then put both clients in NH, and speak with the non iniswapped.
2022-07-10 14:59:47|681025||Newbie Hole|Layton|Namper|NampiGuy|0|0|Vanilla|64|And done.
2022-07-10 14:59:54|681025||Newbie …
```

reset pair on area change

---

server/commands/character.py

as per #51 mods can now /sneak and /unsneak a user. /charselect now works as intended (before it checked if the targeted player was a mod rather than the player using it)

Fixing /charselect, adding ability for mod to force (un)sneak 

---

server/commands/admin.py
server/commands/hubs.py

A command to change the hp of area(s). If no optional area argument is provided, will change all areas.
Otherwise, changes all space-separated areas provided after the HP
Example: `/hpset def 5 0 1 2 3` sets HP 5 to areas 0, 1, 2, 3 for def position.

New /hpset command

---

server/area.py
server/network/aoprotocol.py

the message delay could be bypassed with blankposts because of a division by zero resulting in 0 because we discard all exceptions
and this logs ooc commands like other messages too so you can figure out how the next amazing exploit works

Fix delay being 0 for blankpost and log OOC commands

---

server/network/aoprotocol.py

Allows the user to be able to swap emotes in real time by making use of **Emote Tags** and **Auto-Additive**.
It was made with my AO fork in mind for faster swapping, so it may need some adjustments. Probably changing the delimiters to another character, but I'll leave that up to discuss.
So, how to use? An emote tag looks like this: ¨(emote name)¨ 
The server will scan your message looking for these tags, and if it finds one, it will swap your sprite to whatever emote you added inside the tag.
Example:
https://github.com/Crystalwarrior/KFO-Server/assets/81326989/831a46a0-54e9-457e-b593-cada4c4cfcb9

Presenting the Emote Queue: Mid-Text Emote Swapping

---

server/network/masterserverclient.py

It fixes a bug where the server would randomly disappear from the master-list without even knowing why.
That issue was caused by a missing error handling for the case where the hosting server didn't have an internet connection after the sleep period of 60 seconds.
Additionally, the error printing got updated to provide more detailed information.

[Master-server] Handle the missing error cases 

---

config_sample/config.yaml
server/network/masterserverclient.py

Add advertising secure websocket to MS, so it can advertise that the server can accept encrypted connections(wss), which are also preferable from a security and privacy point of view. As the application server, it should in principle not be burdened with decryption and managing certificates. It is better to configure this on either a reverse proxy (eg. nginx) or do it through cloudflare. It would be best to create additional documentation on how to set this up correctly.
I'm assuming that for most "small" servers setting this up isn't a realistic option, but it could make sense for the bigger servers.
This will also require a (hopefully small) change in MS too (adding wss_port field), so looping in @oldmud0

Add advertising for secure websocket

---

server/area.py
server/client_manager.py
server/commands/areas.py
server/network/aoprotocol.py

- Adds the /overlay ooc command with a "overlay_lock" option, working the same as "bg_lock". 
- Implements the extended BN (background change) packet from AOG 1.0
**Manages the new CU packet of AOG 1.0**
Added a new variable of "client.char_url" used to store the URL of the character the person is using, so everyone else can download it more easily without needing to share the URL every single time manually.
The CU packet is sended everytime the client changes their character.
The client is expected  to send their CU packets on the  "user authority level".
The server can declare their URLs too with the "server authority level".
They are global URLs compared to the user's ones that are per-area
AOG 1.0 client implementation:
The URL on the client is loaded from a "Download.ini" located on …

Initial AOG 1.0 RC1 release

---

server/area.py
server/area_manager.py
server/client_manager.py
server/commands/__init__.py
server/constants.py
server/evidence.py
server/exceptions.py
server/logger.py
server/network/aoprotocol.py
server/network/aoprotocol_ws.py
server/network/masterserverclient.py
server/tsuserver.py
start_server.py

Some really big code projects have copyright notices in every file because their lawyers told them to, but as a general rule they are not necessary.
Removing them makes it a bit easier to read the code since you don't have to scroll down a bunch of lines.
Closes #98

Remove copyright notices in files

---

start-unix.sh

the options on line 3 aren't valid for normal sh, so it may fail on some systems

Use bash for unix-start

---

config_sample/command_aliases.yaml
server/client_manager.py
server/commands/areas.py
server/commands/character.py

Continuation of #100 and #102 
> ~Nothing sets char_url yet right? I suppose a simple command to do so should be added later on?~ Ahh the char_url is set by AOG client, I see. Commands could be added so the system can still be used on pre-AOG clients in a different PR
I put a " " after each link, because AO2 would think that "\n" doesn't break the hyper-link markdown, while " " does.
An issue should be made for it.
- Add the /getlink and /getlinks commands. They work exactly like /getarea and /getareas, but it includes the client link at the end of each.
- Add /get_urls, that gives all the server-side URLs declared on server_links.yaml in the same syntax (doesn't include comments tho)
- Gave every new command added (getlink, getlinks, get_urls) shortcuts on the command_aliases.yaml file.

Add the ability to use the DL Manager functionality outside of AOG

---

server/client_manager.py
server/commands/messaging.py

I rewrote get_targets in client_manager, so that now it can find players also in other hubs. (Maybe in future we can also change /ban so that it can find players in a different hub)

/pm now works if target is in a different hub

---

config_sample/config.yaml
server/commands/admin.py
server/network/webhooks.py

I think it would be useful to know when and who logged in with a mod password from discord. It could also help determine when someone's modpass may have been compromised. 
The code isn't too pretty since it was derived from the modcall webhook but it seems to have worked on my live server.

Allow discord bot to log when modpass login occurs

---

server/area.py
server/commands/casing.py

70% of the valid voters must vote
AFKers, CMs, hidden players, spectators, and people already in a minigame don't count

/concede when outside minigame will vote to end it

---

server/network/aoprotocol.py

This allows players and GMs to easier deliminate action text. Here's how it works:
* If the text contains [, | or * characters, it is recognized as an action.
* If the text is using the Orange color 3, it's recognized as an action.
* Exception: if the text only has *, and ends on a single *, it's not recognized as an action

Highlight people's action syntax in the OOC for easier tracking for both players and GMs

---

server/client_manager.py
server/commands/__init__.py
server/commands/casing.py
server/commands/inventory.py
server/evidence.py
server/network/aoprotocol.py

Add inventory mechanics that are saved on a per-character basis!!!!
* When you delete a piece of evidence as a non-GM char, it will be *added* to your /inventory
* You can drop it back into the area using /inventory_drop <id>
GM commands:
* /inventory_get <id>
* /inventory_add <target> [evi_name/id]
* /inventory_remove <target> <evi_name/id>
* /inventory_edit <target> <evi_name/id> [name] [desc] [image]

Add character inventory mechanics
